- name: Check rds state in groups
  hosts: "{{ service }}"
  vars:
    anansiblevar_python_interpreter: /usr/bin/python3
  connection: local

  tasks:
  - name: Executing query in each host and sending emails
    local_action: command python3 ~/postgresql/common/custom_rds_query.py --profile {{ profile }} --rds-instance {{ inventory_hostname }} --file {{ file }} --list-users "{{ users }}"
    when:  users is defined
    register: result
  - name: Executing query in each host
    local_action: command python3 ~/postgresql/common/custom_rds_query.py --profile {{ profile }} --rds-instance {{ inventory_hostname }} --file {{ file }}
    when: users is undefined
    register: result
  - name: Debugging MySQL Database Quantity
    debug:
      #msg: "{{ (result.stdout |  selectattr('title', 'search', 'Result') | list | first).value }}"
      msg: "{{ result.stdout }}"
    when: '"stdout" in result.keys()'